image: python

stages:
- test
- build
- release

before_script:
- curl -O https://bootstrap.pypa.io/get-pip.py
- python get-pip.py
- pip install -r dev-requirements.txt

python2:
  image: python:2.7
  stage: test
  script: tox -e py27

python3:
  stage: test
  script: tox --skip-missing-interpreters -e py34,py35

linters:
  stage: test
  script: tox -e linters

docs:
  stage: test
  script: tox -e docs

dogfood:
  stage: test
  script: tox -e dogfood

build:
  stage: build
  script: tox -e build
  artifacts:
    paths:
    - dist/
    expire_in: 1 month

release:
  stage: release
  script: tox -e build
  artifacts:
    paths:
    - dist
  only:
  - tags
